// <auto-generated />
using System;
using Mercadorias.Infra.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mercadorias.Infra.Repository.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20230612213616_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mercadorias.Domain.Entities.Entrada", b =>
                {
                    b.Property<Guid>("IdEntrada")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdMercadoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalEntrada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeEntrada")
                        .HasColumnType("int");

                    b.HasKey("IdEntrada");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("Mercadorias.Domain.Entities.Mercadoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Mercadoria");
                });

            modelBuilder.Entity("Mercadorias.Domain.Entities.Saida", b =>
                {
                    b.Property<Guid>("IdSaida")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdMercadoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalSaida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeSaida")
                        .HasColumnType("int");

                    b.HasKey("IdSaida");

                    b.ToTable("Saida");
                });

            modelBuilder.Entity("Mercadorias.Domain.Entities.Entrada", b =>
                {
                    b.HasOne("Mercadorias.Domain.Entities.Mercadoria", "Mercadoria")
                        .WithMany("Entradas")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mercadoria");
                });

            modelBuilder.Entity("Mercadorias.Domain.Entities.Saida", b =>
                {
                    b.HasOne("Mercadorias.Domain.Entities.Mercadoria", "Mercadoria")
                        .WithMany("Saidas")
                        .HasForeignKey("IdSaida")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mercadoria");
                });

            modelBuilder.Entity("Mercadorias.Domain.Entities.Mercadoria", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Saidas");
                });
#pragma warning restore 612, 618
        }
    }
}
